import type { Metadata } from "next";
import "./globals.css";
import Notification from "@/components/Notification";
import AuthSession from "@/components/AuthSession";

export const metadata: Metadata = {
    title: "Next E-Shop",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AuthSession>
            <html lang="en">
                <body suppressHydrationWarning={true}>
                    {children}
                    <Notification />
                </body>
            </html>
        </AuthSession>
    );
}
