import type { Metadata } from "next";
import "./globals.css";
import Notification from "@/components/Notification";
import AuthSession from "@/components/AuthSession";
import localFont from "next/font/local";

export const metadata: Metadata = {
    title: "Next E-Shop",
    description: "Generated by create next app",
};

const myFont = localFont({
    src: "./fonts/pt-serif_regular.woff2",
    display: "swap",
});
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AuthSession>
            <html lang="en">
                <body className={myFont.className} suppressHydrationWarning={true}>
                    {children}
                    <Notification />
                </body>
            </html>
        </AuthSession>
    );
}
